# Generated by Django 4.0.4 on 2022-07-31 14:19

from django.db import migrations, models
import posts.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('title', models.CharField(max_length=1024, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('media', models.FileField(blank=True, null=True, upload_to=posts.utils.upload_file, validators=[posts.utils.PictureAndVideoValidator])),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('hashtags', models.ManyToManyField(blank=True, related_name='post', to='posts.hashtag')),
            ],
        ),
    ]
