# Generated by Django 3.2.7 on 2021-09-30 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_applyforjob_noncooperationdate'),
        ('Posts', '0002_alter_post_hashtag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='tag',
        ),
        migrations.AddField(
            model_name='comment',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='commentReply', to='users.Wallet'),
        ),
    ]
