# Generated by Django 3.2.7 on 2021-09-30 11:59

import Posts.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, unique=True)),
                ('status', models.CharField(choices=[('a', 'accepted'), ('w', 'waiting'), ('r', 'rejected')], default='w', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profilePic', models.ImageField(blank=True, upload_to=Posts.utils.upload_profilePic)),
                ('companyName', models.CharField(max_length=2048)),
                ('about', models.TextField(blank=True)),
                ('workEmail', models.EmailField(blank=True, max_length=254)),
                ('phoneNumber', models.CharField(blank=True, max_length=15)),
                ('website', models.CharField(blank=True, max_length=500)),
                ('foundedIn', models.DateField()),
                ('employeeCount', models.CharField(blank=True, max_length=1024)),
                ('needEmployee', models.BooleanField()),
                ('status', models.CharField(choices=[('a', 'accepted'), ('w', 'waiting'), ('r', 'rejected')], default='w', max_length=1)),
                ('category', models.ManyToManyField(blank=True, related_name='companyProfile', to='users.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Industries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024, unique=True)),
                ('status', models.CharField(choices=[('a', 'accepted'), ('w', 'waiting'), ('r', 'rejected')], default='w', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='ReportReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=2048)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024, unique=True)),
                ('industry', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='tech', to='users.industries')),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('reported', models.BooleanField(default=False)),
                ('following', models.ManyToManyField(blank=True, related_name='followers', to='users.Wallet')),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('company', models.CharField(max_length=1024)),
                ('start', models.DateField()),
                ('end', models.DateField(blank=True, null=True)),
                ('stillWorking', models.BooleanField()),
                ('description', models.TextField(blank=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workExperience', to='users.wallet')),
                ('tech', models.ManyToManyField(blank=True, related_name='workExperience', to='users.Tech')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024, unique=True)),
                ('industry', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='role', to='users.industries')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.TextField()),
                ('slugTo', models.URLField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('markAsRead', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification', to='users.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField()),
                ('text', models.TextField(blank=True)),
                ('category', models.ManyToManyField(related_name='jobOffer', to='users.Category')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobOffer', to='users.company')),
                ('tech', models.ManyToManyField(blank=True, related_name='jobOffer', to='users.Tech')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('profilePic', models.ImageField(blank=True, upload_to=Posts.utils.upload_profilePic)),
                ('about', models.TextField(blank=True)),
                ('address', models.CharField(blank=True, max_length=1024)),
                ('phoneNumber', models.CharField(max_length=13)),
                ('birthday', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('D', "Don't wanna say")], max_length=1)),
                ('relationshipStatus', models.CharField(choices=[('S', 'Single'), ('M', 'Married')], max_length=1)),
                ('jobSearchStatus', models.CharField(choices=[('A', 'Actively looking right now'), ('O', 'Open, but not actively looking'), ('N', 'Not interested in jobs')], max_length=1)),
                ('minimumAnnualSalary', models.PositiveIntegerField(blank=True, null=True)),
                ('jobType', models.CharField(blank=True, choices=[('F', 'Full-time'), ('C', 'Contract'), ('I', 'Internship')], max_length=1)),
                ('hire', models.BooleanField()),
                ('category', models.ManyToManyField(blank=True, related_name='employeeProfile', to='users.Category')),
                ('industries', models.ManyToManyField(blank=True, related_name='employeeProfileIndustries', to='users.Industries')),
                ('industriesToExclude', models.ManyToManyField(blank=True, related_name='employeeProfileIndustriesToExclude', to='users.Industries')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employeeProfile', to='users.wallet')),
                ('role', models.ManyToManyField(blank=True, related_name='employeeProfile', to='users.Role')),
                ('techWantsToNotWorkWith', models.ManyToManyField(blank=True, related_name='employeeProfileTechWantsToNotWorkWith', to='users.Tech')),
                ('techWantsToWorkWith', models.ManyToManyField(blank=True, related_name='employeeProfileTechWantsToWorkWith', to='users.Tech')),
            ],
        ),
        migrations.CreateModel(
            name='EducationalBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grad', models.CharField(max_length=1024)),
                ('major', models.CharField(max_length=1024)),
                ('educationalInstitute', models.CharField(max_length=1024)),
                ('start', models.DateField()),
                ('end', models.DateField(blank=True, null=True)),
                ('stillStudying', models.BooleanField()),
                ('adjusted', models.DecimalField(decimal_places=2, max_digits=4)),
                ('description', models.TextField(blank=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educationalBackground', to='users.employee')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to=Posts.utils.upload_companyDocument)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companyDocument', to='users.company')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='industries',
            field=models.ManyToManyField(blank=True, related_name='companyProfile', to='users.Industries'),
        ),
        migrations.AddField(
            model_name='company',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.wallet'),
        ),
        migrations.AddField(
            model_name='category',
            name='industry',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='users.industries'),
        ),
        migrations.AddField(
            model_name='category',
            name='upperCategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reverseCategory', to='users.category'),
        ),
        migrations.CreateModel(
            name='ApplyForJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('e', 'employee'), ('c', 'company')], max_length=1)),
                ('text', models.TextField()),
                ('status', models.CharField(choices=[('w', 'waiting'), ('a', 'accepted'), ('r', 'rejected')], default='w', max_length=1)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applyForJob', to='users.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applyForJob', to='users.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('certificateProvider', models.CharField(max_length=1024)),
                ('date', models.DateField()),
                ('siteAddress', models.CharField(blank=True, max_length=1024)),
                ('description', models.TextField(blank=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievement', to='users.wallet')),
            ],
        ),
    ]
