# Generated by Django 4.0.4 on 2022-07-31 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Industries',
            new_name='Industry',
        ),
        migrations.AlterField(
            model_name='achievement',
            name='siteAddress',
            field=models.URLField(blank=True, max_length=1024),
        ),
    ]
