# Generated by Django 3.2.7 on 2021-09-30 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_notification_notification_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='slugTo',
        ),
        migrations.AddField(
            model_name='notification',
            name='slug',
            field=models.SlugField(default=2),
            preserve_default=False,
        ),
    ]
