# Generated by Django 3.2.7 on 2021-09-30 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210930_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
