# Generated by Django 3.2.7 on 2021-09-30 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_notification_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.URLField()),
                ('description', models.TextField(blank=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('reasons', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportPost', to='users.reportreason')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportPost', to='users.wallet')),
            ],
        ),
    ]
