# Generated by Django 3.2.7 on 2021-09-30 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyforjob',
            name='non_cooperation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wallet',
            name='block',
            field=models.ManyToManyField(blank=True, related_name='blockBy', to='users.Wallet'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='private',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='report',
            name='slug',
            field=models.SlugField(),
        ),
    ]
