# Generated by Django 3.2.7 on 2021-09-30 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210930_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
