# Generated by Django 3.2.7 on 2021-09-30 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_wallet_private'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='reported',
            new_name='ban',
        ),
    ]
