# Generated by Django 3.2.7 on 2021-09-30 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_applyforjob_noncooperationdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='title',
            field=models.CharField(default='', max_length=1024),
            preserve_default=False,
        ),
    ]
