# Generated by Django 3.2.7 on 2021-09-30 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_joboffer_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Role',
            new_name='Job',
        ),
        migrations.AddField(
            model_name='joboffer',
            name='job',
            field=models.ManyToManyField(blank=True, related_name='jobOffer', to='users.Job'),
        ),
    ]
