# Generated by Django 3.2.7 on 2021-09-30 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20211001_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='jobType',
            field=models.CharField(blank=True, choices=[('F', 'Full-time'), ('C', 'Contract'), ('I', 'Internship'), ('R', 'Remote')], max_length=1),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='salary',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
