# Generated by Django 4.0.4 on 2022-07-31 14:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='question', to='users.category'),
        ),
        migrations.AddField(
            model_name='question',
            name='downVote',
            field=models.ManyToManyField(blank=True, related_name='questionDownVote', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='techs',
            field=models.ManyToManyField(blank=True, related_name='question', to='users.tech'),
        ),
        migrations.AddField(
            model_name='question',
            name='upVote',
            field=models.ManyToManyField(blank=True, related_name='questionUpVote', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answer',
            name='downVote',
            field=models.ManyToManyField(blank=True, related_name='answerDownVote', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answer',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='questions.question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='upVote',
            field=models.ManyToManyField(blank=True, related_name='answerUpVote', to=settings.AUTH_USER_MODEL),
        ),
    ]
